name: git tag release and npm package publisher
on:
  push:
    branches:
      - master
jobs:
  publish_tag_package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master

    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '16.20.2'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@tivic-team'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        npm i
        npm run build
    - run: |
        git config --global user.email "${{ github.actor }}@noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        echo "${{ steps.bump_version.outputs.tag }}" 
    - run: npm version -f "${{ steps.bump_version.outputs.tag }}" --allow-same-version && npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
